sudo: required
cache:
  directories:
    - $HOME/google-cloud-sdk
env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - if [ ! -d $HOME/google-cloud-sdk/bin ]; then
      rm -rf $HOME/google-cloud-sdk;
      curl https://sdk.cloud.google.com | bash > /dev/null;
    fi
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project udemy-multi-k8s-274006
  - gcloud config set compute/zone us-east1-b
  - gcloud container clusters get-credentials multi-cluster
